### ISSUE TITLE
Unable to Configure Meteor

### ISSUE THREAD

**Issue by rlugge** [djluck/accounts-azure-active-directory#2]
Documentation seems to be missing a step on how to configure a Meteor app -- where exactly am I supposed to find a 'configure Azure AD' button?  How does that help me make a connection between my environment variables and accounts-azure-active-directory -- shouldn't that be done through code at application start-up?

**Comment by djluck** [comment]
Read this - http://guide.meteor.com/accounts.html#accounts-ui. The key part is adding the {{ > loginButtons }} template- this is what will render the login menu and the "Configure Azure AD" button. 

As for configuring the application programaticaly, you can always modify the monogDb values directly. I can't provide a walk-through on this (it's been a long time since I've worked with Meteor) but if you inspect the values of your MongoDb instance AFTER configuring the Azure AD OAuth provider, you should have an idea of what needs to be done.

**Comment by rlugge** [comment]
It actually proved very simple once I dug into your code & documentation for Meteor OAuth.  Meteor has some absolutely insane conventions.  Putting this type of thing into the DB is...  well, it doesn't belong there, and I'm shocked it's getting put there.

```
import { ServiceConfiguration } from 'meteor/service-configuration'

Meteor.startup(function() {
  ServiceConfiguration.configurations.upsert( { service: 'azureAd' }, {
    $set: {
      clientId: process.env.AZURE_ACTIVE_DIRECTORY_CLIENT_ID,
      secret: process.env.AZURE_ACTIVE_DIRECTORY_SECRET_KEY,
      tennantId: process.env.AZURE_ACTIVE_DIRECTORY_TENANT_ID
    }
  });
});
```
